### ISSUE TITLE
Prepend module and class names to method symbols

### ISSUE THREAD

**Issue by FichteFoll** [SublimeText/sublime-text-docset#1]
Will probably use a Python script, as we need to parse the html but rename the symbol in the compiled docset.

**Comment by FichteFoll** [comment]
I took a brief look and it looks like the index is a binary format. Will probably check the dashing code to see which format.

**Comment by michaelblyons** [comment]
Haha. I thought you were going to make a hidden `<span>` in the HTML with the module/class name on each `<td>`. Editing the sqlite directly is at least as good as that.
