### ISSUE TITLE
Aquire permission to redistribute the official documentation as an offline docset

### ISSUE THREAD

**Issue by FichteFoll** [SublimeText/sublime-text-docset#10]
The official documentation is copyrighted by Sublime Hq Pty Ltd Py. While we are able to build a docset from it (or rather provide the instructions on how to do so), we are not allowed to redistribute the documentation, so that people could download the docset within their Dash or Zeal app. They have to build it themselves and import it locally.

As far as I know, Jon is the person to ask for such questions, but maybe also kari. I reached out to Jon via Discord, but he has not replied yet. Sending an email to the sales mail account and kari might be more promising.

I personally doubt that we would be sued for redistributing the documention, since we're not defaming them or making a profit, and I don't want to bother with the technically required paperwork for receiving an explicit permit or license. I'm hoping a verbal consent in any form will be enough for them not to actually sue anyone *and* it is definitely in my personal interest to have at least the inofficial permission to do so.

Since Dash is a commercial product, I could see the possibility of not being allowed to add a built docset to Dash's default feed. I have also never used Dash and don't know the process of adding a docset.
Zeal, however, is open source and allows adding custom feeds in their settings dialog. I just don't know the format (yet).

**Comment by michaelblyons** [comment]
Hooray! Jon replied with

> no problem re: docs

**Comment by FichteFoll** [comment]
For documentation purposes:

> [2020-05-15 21:35 CET] FichteFoll: @ jps I would like to offer a compiled version of a Dash/Zeal docset for ST based on the official documentation. Currently we only provide the steps to build such a docset at https://github.com/SublimeText/sublime-text-docset, because the docs are of course copyrighted. Can I aquire your approval to do so?

https://discordapp.com/channels/280102180189634562/280157067396775936/710938374546129007

> [2018-05-18 08:43 CET] jps: @ FichteFoll no problem re: docs

https://discordapp.com/channels/280102180189634562/280157067396775936/711831267347398666

---

Considering the docs are for the current alpha builds and not yet to be shared too publicly, I want to wait for the first dev build to be officially released until we advertise the docset and add it to official channels, but we can certainly work on automation until then.
